name: CI/CD Pipeline

on:
  push:
    # Este workflow se activará solo cuando se cree un nuevo tag (ej. v1.0.1)
    tags:
      - 'v*.*.*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permisos para escribir en el repositorio
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          # Extrae la versión directamente del tag de Git que activó el workflow
          tags: ${{ secrets.DOCKER_USERNAME }}/microagente-resumen-ia:${{ github.ref_name }}